model_list:
  - model_name: deepseek-r1
    litellm_params:
      model: deepseek/deepseek-reasoner
      api_base: https://api.deepseek.com
      api_key: "os.environ/DEEPSEEK_API_KEY"
  - model_name: deepseek-v3.2
    litellm_params:
      model: deepseek/deepseek-chat
      api_base: https://api.deepseek.com
      api_key: "os.environ/DEEPSEEK_API_KEY"
  - model_name: kimi-latest-8k
    litellm_params:
      model: moonshot/kimi-latest-8k
      api_base: https://api.moonshot.cn/v1
      api_key: "os.environ/MOONSHOT_API_KEY"
  - model_name: kimi-latest-32k
    litellm_params:
      model: moonshot/kimi-latest-32k
      api_base: https://api.moonshot.cn/v1
      api_key: "os.environ/MOONSHOT_API_KEY"
  - model_name: kimi-latest-128k
    litellm_params:
      model: moonshot/kimi-latest-128k
      api_base: https://api.moonshot.cn/v1
      api_key: "os.environ/MOONSHOT_API_KEY"
  - model_name: kimi-k2.5
    litellm_params:
      model: moonshot/kimi-k2.5
      api_base: https://api.moonshot.cn/v1
      api_key: "os.environ/MOONSHOT_API_KEY"
